### PR TITLE
Fix VKontakte version for API requests

### PR DESCRIPTION
**Pull request by mxp100**
Fix. Version required. Compliant with Provider - VK API v. 3.0

### CODE REVIEW

**Comment by mxp100** [comment]
added version for compatibility with the new api

**Comment by Xmk** [comment]
important fix ) thx

**Comment by faustbrian** [comment]
Why is one version 3 and the other 5? This also looks like an attribute that should be configurable as versions change over time.

**Comment by faustbrian** [comment]
Also PRs goes go to https://github.com/SocialiteProviders/Providers so this one will be closed.

**Comment by mxp100** [comment]
Yes version 5 used for OAuth (no changes in VK) and for backward compatible with Provider uses version 3.0, it's a work on my projects

**Comment by Xmk** [comment]
@faustbrian check working vk auth before closed pr, lol

**Comment by mxp100** [comment]
@faustbrian In the current performance, the provider does not work, with my fix everything will work. On good, it is necessary to rewrite the whole provider for new versions of API. Or may be you write fix?

**Comment by faustbrian** [comment]
As I said, PRs goes to https://github.com/SocialiteProviders/Providers and not this repository.

**Pull request closed without merging**
