### PR TITLE
Global fix the driver

### PR DESCRIPTION
**Pull request by AndrewNovikof**
Delete useless methods. Correction of the logic of receiving a user via access_token

### CODE REVIEW

**Comment by faustbrian** [comment]
PRs go to https://github.com/SocialiteProviders/Providers.

**Comment by AndrewNovikof** [comment]
What you mean?

**Comment by AndrewNovikof** [comment]
Take PR, because the driver does not work correctly. And create the next version to not break the compatibility of the old one.

**Comment by faustbrian** [comment]
As I already said, PRs go to https://github.com/SocialiteProviders/Providers not the the Provider repositories itself.

Provider repositories are just subtree-splits of the providers repository for packagist.

**Pull request closed without merging**
