### PR TITLE
photo size big

### PR DESCRIPTION
**Pull request by devourersouls**

### CODE REVIEW

**Comment by faustbrian** [comment]
Does the photo attribute no longer exist?

**Comment by devourersouls** [comment]
the attribute "photo" raises the image of very poor quality

**Comment by faustbrian** [comment]
@devourersouls Please resolve the conflicts, will merge after that.

**Comment by eupathy** [comment]
Please, accept this pull request,because now avatar too small

**Comment by faustbrian** [comment]
This repository is read-only. Please send this PR to https://github.com/SocialiteProviders/Providers.

**Pull request closed without merging**
